/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/UI/Button/Button.vue')['default']
    component: typeof import('vue')['component']
    Container: typeof import('./src/components/Container/Container.vue')['default']
    IconSprite: typeof import('./src/components/UI/IconSprite/IconSprite.vue')['default']
    Modal: typeof import('./src/components/UI/Modal/Modal.vue')['default']
    Notification: typeof import('./src/components/UI/Notification/Notification.vue')['default']
    Settings: typeof import('./src/components/Settings/Settings.vue')['default']
    TaskCategory: typeof import('./src/components/TaskCategory/TaskCategory.vue')['default']
    TaskItem: typeof import('./src/components/TaskItem/TaskItem.vue')['default']
    TaskItemForm: typeof import('./src/components/TaskItemForm/TaskItemForm.vue')['default']
    TasksBoard: typeof import('./src/components/TasksBoard/TasksBoard.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter/TheFooter.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader/TheHeader.vue')['default']
  }
}
